odometry_localization:
  ros__parameters:
    update_rate: 60.0

    wheel_base: 0.19
    wheel_radius: 0.051

pid_path_generator:
  ros__parameters:
    waypoints_json: |
      [
        { "x": 0.6, "y": 0.0 },
        { "x": 1.2, "y": 0.6 },
        { "x": 1.8, "y": 0.6 },
        { "x": 2.4, "y": 0.0 }
      ]
    min_waypoint_distance: 0.1
    max_waypoint_distance: 2.0

pid_point_controller:
  ros__parameters:
    update_rate: 30.0

    Kp_V: 0.15
    Ki_V: 0.0
    Kd_V: 0.0

    Kp_Omega: 0.09
    Ki_Omega: 0.0
    Kd_Omega: 0.0

    goal_tolerance: 0.08
    heading_tolerance: 0.09

    min_linear_vel: 0.1
    max_linear_vel: 0.17

    min_angular_vel: -0.15
    max_angular_vel: 0.15

    velocity_scale_factor: 1.0