line_detection:
  ros__parameters:
    image_topic: 'image_raw'
    use_compressed: True

    update_rate: 30.0

    target_width: 640
    target_height: 480

    perspective_tl_x: 190
    perspective_tl_y: 350
    perspective_bl_x: 190
    perspective_bl_y: 479
    perspective_tr_x: 450
    perspective_tr_y: 350
    perspective_br_x: 450
    perspective_br_y: 479

    gaussian_kernel_size: 5
    gaussian_sigma: 5

    grayscale_threshold: 95
    morph_kernel_size: 3
    morph_erode_iterations: 40
    morph_dilate_iterations: 90

    min_contour_area: 180
    max_contour_area: 500000

    filter_alpha: 0.1

line_follow_controller:
  ros__parameters:
    update_rate: 30.0

    linear_velocity: 0.07

    Kp_Omega: 0.35
    Ki_Omega: 0.1
    Kd_Omega: 0.1

    max_angular_speed: 1.5

    velocity_scale_factor: 1.0
    steering_deadband: 0.03