color_blob_detection:
  ros__parameters:
    image_topic: 'image_raw'
    use_compressed: True

    update_rate: 30.0
    
    hsv_green_h_low: 50
    hsv_green_s_low: 35
    hsv_green_v_low: 40
    hsv_green_h_high: 110
    hsv_green_s_high: 255
    hsv_green_v_high: 255
    
    hsv_yellow_h_low: 15
    hsv_yellow_s_low: 40
    hsv_yellow_v_low: 90
    hsv_yellow_h_high: 40
    hsv_yellow_s_high: 255
    hsv_yellow_v_high: 255
    
    hsv_red1_h_low: 0
    hsv_red1_s_low: 60
    hsv_red1_v_low: 100
    hsv_red1_h_high: 10
    hsv_red1_s_high: 255
    hsv_red1_v_high: 255
  
    hsv_red2_h_low: 160
    hsv_red2_s_low: 60
    hsv_red2_v_low: 100
    hsv_red2_h_high: 180
    hsv_red2_s_high: 255
    hsv_red2_v_high: 255
    
    blob_min_threshold: 10
    blob_max_threshold: 250
    blob_min_area: 200
    blob_max_area: 10000000
    blob_min_convexity: 0.5
    blob_max_convexity: 1.0
    blob_min_circularity: 0.8
    blob_max_circularity: 1.0
    blob_min_inertia_ratio: 0.2
    blob_max_inertia_ratio: 1.0
    
    gaussian_kernel_size_width: 9
    gaussian_kernel_size_height: 9
    gaussian_sigma: 5
    grayscale_threshold: 10 
    morph_kernel_size_width: 3
    morph_kernel_size_height: 3
    morph_erode_iterations: 10
    morph_dilate_iterations: 8

yolov8_recognition:
  ros__parameters:
    image_topic: 'image_raw'
    use_compressed: True
    
    model_name: 'puzzlebot_traffic_signs.pt'
    confidence_threshold: 0.3
    update_rate: 15.0

line_detection:
  ros__parameters:
    image_topic: 'image_raw'
    use_compressed: True

    update_rate: 30.0

    target_width: 640
    target_height: 480

    perspective_tl_x: 190
    perspective_tl_y: 350
    perspective_bl_x: 190
    perspective_bl_y: 479
    perspective_tr_x: 450
    perspective_tr_y: 350
    perspective_br_x: 450
    perspective_br_y: 479

    gaussian_kernel_size: 5
    gaussian_sigma: 5

    grayscale_threshold: 95
    morph_kernel_size: 3
    morph_erode_iterations: 40
    morph_dilate_iterations: 40

    min_contour_area: 180
    max_contour_area: 500000

    filter_alpha: 0.1

line_follow_controller:
  ros__parameters:
    update_rate: 30.0

    linear_velocity: 0.07

    Kp_Omega: 0.35
    Ki_Omega: 0.1
    Kd_Omega: 0.1

    max_angular_speed: 1.5

    velocity_scale_factor: 1.0
    steering_deadband: 0.03

traffic_fsm:
  ros__parameters:
    update_rate: 30.0

    detection_timeout: 1.0

    full_speed_scale: 1.0
    mid_speed_scale: 0.6

    controller_on_service: 'line_follow_controller/controller_on'        
    controller_parameter_service: 'line_follow_controller/set_parameters'

    stop_sign_min_area: 0.1

    straight_intersection_linear_vel: 0.06

    turn_intersection_linear_vel: 0.06
    turn_intersection_angular_vel: 1.0

    turn_forward_distance:  0.35
    turn_rotation_angle: 1.57

    image_width: 640
    image_height: 480

    sign_ahead_class: 'fwd'
    sign_right_class: 'right'
    sign_left_class: 'left'
    sign_roadwork_class: 'triUp'
    sign_stop_class: 'stop'
    sign_giveway_class: 'triDwn'