yolov8_recognition:
  ros__parameters:
    model_name: 'puzzlebot_traffic_signs.pt'
    confidence_threshold': 0.3
    update_rate: 10.0

line_follow_controller:
  ros__parameters:
    update_rate: 30.0
    linear_velocity: 0.07
    Kp_Omega: 0.38
    Ki_Omega: 0.1
    Kd_Omega: 0.1
    max_angular_speed: 1.5
    line_timeout: 0.5
    velocity_scale_factor: 1.0
    steering_deadband: 0.06

line_detection:
  ros__parameters:
    update_rate: 30.0
    target_width: 640
    target_height: 480
    perspective_tl_x: 218
    perspective_tl_y: 350
    perspective_bl_x: 210
    perspective_bl_y: 460
    perspective_tr_x: 410
    perspective_tr_y: 350
    perspective_br_x: 410
    perspective_br_y: 460
    gaussian_kernel_size: 5
    gaussian_sigma: 5
    grayscale_threshold: 220
    morph_kernel_size: 3
    morph_erode_iterations: 60
    morph_dilate_iterations: 70
    min_contour_area: 300
    max_contour_area: 5000000
    filter_alpha: 0.1
    min_line_continuity_area: 15000
    min_line_height: 100

traffic_fsm:
  ros__parameters:
    update_rate: 30.0
    detection_timeout: 0.8
    full_speed_scale: 1.0
    mid_speed_scale: 0.6
    pid_toggle_service: 'line_pid/pid_toggle'
    pid_parameter_service: 'line_follow_controller/set_parameters'
    stop_sign_min_area: 0.1
    intersection_linear_vel: 0.2
    intersection_angular_vel: 0.5
    image_width: 640
    image_height: 480
    sign_ahead_class: 'fwd'
    sign_right_class: 'right'
    sign_left_class: 'left'
    sign_roadwork_class: 'triUp'
    sign_stop_class: 'stop'
    sign_giveway_class: 'triDwn'

color_blob_detection:
  ros__parameters:
    update_rate: 30.0
    debug_view: false
    hsv_red1_low: [0, 60, 100]
    hsv_red1_high: [10, 255, 255]
    hsv_red2_low: [160, 60, 100]
    hsv_red2_high: [180, 255, 255]
    hsv_green_low: [50, 35, 40]
    hsv_green_high: [110, 255, 255]
    hsv_yellow_low: [15, 40, 90]
    hsv_yellow_high: [40 , 255, 255]

    blob_min_threshold: 10
    blob_max_threshold: 250
    blob_min_area: 200
    blob_max_area: 10000000
    blob_min_convexity: 0.5
    blob_max_convexity: 1.0
    blob_min_circularity: 0.8
    blob_max_circularity: 1.0
    blob_min_inertia_ratio: 0.2
    blob_max_inertia_ratio: 1.0

    gaussian_kernel_size: [9, 9]
    gaussian_sigma: 5
    grayscale_threshold: 10
    morph_kernel_size: [3, 3]
    morph_erode_iterations: 10
    morph_dilate_iterations: 8