yolov8_detection:
  ros__parameters:
    image_topic: 'image_raw'
    use_compressed: false
    
    model_name: 'puzzlebot_traffic_signs.pt'
    confidence_threshold: 0.3
    update_rate: 10.0

line_follow_controller:
  ros__parameters:
    update_rate: 30.0
    linear_velocity: 0.07
    Kp_Omega: 0.38
    Ki_Omega: 0.1
    Kd_Omega: 0.1
    max_angular_speed: 1.5
    line_timeout: 0.5
    velocity_scale_factor: 1.0
    steering_deadband: 0.06

line_detection:
  ros__parameters:
    image_topic: 'image_raw'
    use_compressed: false
    update_rate: 30.0
    target_width: 640     
    target_height: 480     
    
    perspective_tl_x: 250  
    perspective_tl_y: 400
    perspective_bl_x: 250  
    perspective_bl_y: 470
    perspective_tr_x: 390  
    perspective_tr_y: 400
    perspective_br_x: 390  
    perspective_br_y: 470
    
    gaussian_kernel_size: 5
    gaussian_sigma: 5
    
    grayscale_threshold: 125
    morph_kernel_size: 3
    morph_erode_iterations: 7
    morph_dilate_iterations: 7
    
    min_contour_area: 500
    max_contour_area: 5000000
    
    filter_alpha: 0.1
    
    min_line_continuity_area: 15000
    min_line_height: 100

traffic_fsm:
  ros__parameters:
    update_rate: 30.0
    detection_timeout: 0.8
    full_speed_scale: 1.0
    mid_speed_scale: 0.6
    pid_toggle_service: 'line_pid/pid_toggle'
    pid_parameter_service: 'line_follow_controller/set_parameters'
    stop_sign_min_area: 0.1
    intersection_linear_vel: 0.2
    intersection_angular_vel: 0.5
    image_width: 640
    image_height: 480

    sign_ahead_class: 'fwd'
    sign_right_class: 'right'
    sign_left_class: 'left'
    sign_roadwork_class: 'triUp'
    sign_stop_class: 'stop'
    sign_giveway_class: 'triDwn'

color_blob_detection:
  ros__parameters:
    image_topic: 'image_raw'
    update_rate: 30.0
    use_compressed: false
    
    hsv_green_h_low: 40
    hsv_green_s_low: 70
    hsv_green_v_low: 70
    hsv_green_h_high: 80
    hsv_green_s_high: 255
    hsv_green_v_high: 255
    
    hsv_yellow_h_low: 20
    hsv_yellow_s_low: 150
    hsv_yellow_v_low: 150
    hsv_yellow_h_high: 35
    hsv_yellow_s_high: 255
    hsv_yellow_v_high: 255
    
    hsv_red1_h_low: 0
    hsv_red1_s_low: 100
    hsv_red1_v_low: 100
    hsv_red1_h_high: 10
    hsv_red1_s_high: 255
    hsv_red1_v_high: 255
    
    hsv_red2_h_low: 160
    hsv_red2_s_low: 100
    hsv_red2_v_low: 100
    hsv_red2_h_high: 180
    hsv_red2_s_high: 255
    hsv_red2_v_high: 255
    
    blob_min_threshold: 30
    blob_max_threshold: 255
    blob_min_area: 30
    blob_max_area: 10000000
    blob_min_convexity: 0.1
    blob_max_convexity: 1.0
    blob_min_circularity: 0.5
    blob_max_circularity: 1.0
    blob_min_inertia_ratio: 0.5
    blob_max_inertia_ratio: 1.0
    
    gaussian_kernel_size_width: 9
    gaussian_kernel_size_height: 9
    gaussian_sigma: 2
    grayscale_threshold: 5
    morph_kernel_size_width: 3
    morph_kernel_size_height: 3
    morph_erode_iterations: 8
    morph_dilate_iterations: 8