color_blob_detection:
  ros__parameters:
    image_topic: 'image_raw'
    use_compressed: True

    update_rate: 30.0
    
    hsv_green_h_low: 50
    hsv_green_s_low: 35
    hsv_green_v_low: 40
    hsv_green_h_high: 110
    hsv_green_s_high: 255
    hsv_green_v_high: 255
    
    hsv_yellow_h_low: 15
    hsv_yellow_s_low: 40
    hsv_yellow_v_low: 90
    hsv_yellow_h_high: 40
    hsv_yellow_s_high: 255
    hsv_yellow_v_high: 255
    
    hsv_red1_h_low: 0
    hsv_red1_s_low: 60
    hsv_red1_v_low: 100
    hsv_red1_h_high: 10
    hsv_red1_s_high: 255
    hsv_red1_v_high: 255
  
    hsv_red2_h_low: 160
    hsv_red2_s_low: 60
    hsv_red2_v_low: 100
    hsv_red2_h_high: 180
    hsv_red2_s_high: 255
    hsv_red2_v_high: 255
    
    blob_min_threshold: 10
    blob_max_threshold: 250
    blob_min_area: 200
    blob_max_area: 10000000
    blob_min_convexity: 0.5
    blob_max_convexity: 1.0
    blob_min_circularity: 0.8
    blob_max_circularity: 1.0
    blob_min_inertia_ratio: 0.2
    blob_max_inertia_ratio: 1.0
    
    gaussian_kernel_size_width: 9
    gaussian_kernel_size_height: 9
    gaussian_sigma: 5
    grayscale_threshold: 10 
    morph_kernel_size_width: 3
    morph_kernel_size_height: 3
    morph_erode_iterations: 10
    morph_dilate_iterations: 8

odometry_localization:
  ros__parameters:
    update_rate: 60.0

    wheel_base: 0.19
    wheel_radius: 0.051

pid_path_generator:
  ros__parameters:
    waypoints_json: |
      [
        { "x": 0.6, "y": 0.0 },
        { "x": 1.2, "y": 0.6 },
        { "x": 1.8, "y": 0.6 },
        { "x": 2.4, "y": 0.0 }
      ]
    min_waypoint_distance: 0.1
    max_waypoint_distance: 2.0

pid_point_controller:
  ros__parameters:
    update_rate: 30.0

    Kp_V: 0.15
    Ki_V: 0.0
    Kd_V: 0.0

    Kp_Omega: 0.09
    Ki_Omega: 0.0
    Kd_Omega: 0.0

    goal_tolerance: 0.08
    heading_tolerance: 0.09

    min_linear_vel: 0.1
    max_linear_vel: 0.17

    min_angular_vel: -0.15
    max_angular_vel: 0.15

    velocity_scale_factor: 1.0

traffic_light_fsm:
  ros__parameters:
    update_rate: 30.0

    color_detection_timeout: 2.0

    green_velocity_scale: 1.0
    yellow_velocity_scale: 0.6

    controller_on_service: 'pid_point_controller/controller_on'
    controller_parameter_service: 'pid_point_controller/set_parameters'